#!/usr/bin/env node
// Fetches yellow/red card events for all WC2026 group-stage matches from API-Football
// and writes them to data/cards.json.
//
// Usage:
//   API_FOOTBALL_KEY=your_key node fetch-cards.mjs
//
// Run once after each matchday, then commit data/cards.json.

import { writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const KEY = process.env.API_FOOTBALL_KEY;
if (!KEY) {
  console.error('Error: set API_FOOTBALL_KEY environment variable');
  process.exit(1);
}

// ─── Same name→code map as app.js ────────────────────────────────────────────

const NAME_TO_CODE = {
  'Mexico': 'MEX', 'South Africa': 'RSA', 'South Korea': 'KOR',
  'Czech Republic': 'CZE', 'Canada': 'CAN', 'Bosnia & Herzegovina': 'BIH',
  'Qatar': 'QAT', 'Switzerland': 'SUI', 'Brazil': 'BRA', 'Morocco': 'MAR',
  'Haiti': 'HAI', 'Scotland': 'SCO', 'USA': 'USA', 'Paraguay': 'PAR',
  'Australia': 'AUS', 'Turkey': 'TUR', 'Germany': 'GER', 'Curaçao': 'CUW',
  'Ivory Coast': 'CIV', 'Ecuador': 'ECU', 'Netherlands': 'NED', 'Japan': 'JPN',
  'Sweden': 'SWE', 'Tunisia': 'TUN', 'Belgium': 'BEL', 'Egypt': 'EGY',
  'Iran': 'IRN', 'New Zealand': 'NZL', 'Spain': 'ESP', 'Cape Verde': 'CPV',
  'Saudi Arabia': 'KSA', 'Uruguay': 'URU', 'France': 'FRA', 'Senegal': 'SEN',
  'Iraq': 'IRQ', 'Norway': 'NOR', 'Argentina': 'ARG', 'Algeria': 'ALG',
  'Austria': 'AUT', 'Jordan': 'JOR', 'Portugal': 'POR', 'DR Congo': 'COD',
  'Uzbekistan': 'UZB', 'Colombia': 'COL', 'England': 'ENG', 'Croatia': 'CRO',
  'Ghana': 'GHA', 'Panama': 'PAN',
};

function nameToCode(name) {
  return NAME_TO_CODE[name] ?? name?.slice(0, 3).toUpperCase() ?? '???';
}

// ─── API helper ───────────────────────────────────────────────────────────────

async function apiFetch(path) {
  const url = `https://v3.football.api-sports.io${path}`;
  const res = await fetch(url, {
    headers: {
      'x-apisports-key': KEY,
      'x-rapidapi-host': 'v3.football.api-sports.io',
    },
  });
  if (!res.ok) throw new Error(`API error ${res.status} for ${url}`);
  const json = await res.json();
  if (json.errors && Object.keys(json.errors).length) {
    throw new Error(`API returned errors: ${JSON.stringify(json.errors)}`);
  }
  return json;
}

// ─── Card type mapping ────────────────────────────────────────────────────────

function mapCardType(detail) {
  switch (detail) {
    case 'Yellow Card':      return 'yellow';
    case 'Red Card':         return 'red';
    case 'Yellow Red Card':  return 'yellow_red';
    default:                 return null;
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Fetching WC2026 fixtures from API-Football…');

  // League 1 = FIFA World Cup, season 2026
  const { response: fixtures } = await apiFetch('/fixtures?league=1&season=2026');
  console.log(`  ${fixtures.length} fixtures returned`);

  const matches = {};
  let matchesWithCards = 0;

  for (const f of fixtures) {
    const { fixture, teams, events, league } = f;

    // Only group stage (round contains "Group")
    if (!league?.round?.includes('Group')) continue;

    const events_ = events ?? [];
    const cardEvents = events_
      .filter(e => e.type === 'Card')
      .map(e => {
        const type = mapCardType(e.detail);
        if (!type) return null;
        return {
          team: nameToCode(e.team?.name ?? ''),
          type,
          player: e.player?.name ?? '',
          minute: e.time?.elapsed ?? null,
        };
      })
      .filter(Boolean);

    if (!cardEvents.length) continue;

    // Match ID must match what normalizeOpenFootball produces: "YYYY-MM-DD-HOME-AWAY"
    const date = fixture.date?.slice(0, 10);
    const homeCode = nameToCode(teams.home.name);
    const awayCode = nameToCode(teams.away.name);
    const matchId = `${date}-${homeCode}-${awayCode}`;

    matches[matchId] = cardEvents;
    matchesWithCards++;
  }

  const output = {
    updated: new Date().toISOString(),
    note: 'Generated by fetch-cards.mjs — do not edit by hand',
    matches,
  };

  const outPath = join(__dirname, 'data/cards.json');
  writeFileSync(outPath, JSON.stringify(output, null, 2));
  console.log(`✓ Wrote ${matchesWithCards} matches with card events to data/cards.json`);
}

main().catch(err => {
  console.error('Failed:', err.message);
  process.exit(1);
});
